# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e0130893b64fa6f5fa7fb8e713256639bccea0453ad3943f610dacceaa56b979996bed0ea992e6dd4dd90cc55f60fb99ea202ba23811f3fe5cbed238e572cda

test:
  secret_key_base: eb5dd1b56b70dd44dffd896234a883b1d289243da5c26e25138998c4f4b651f8005e310aa9e5838ca6d3d7e82a3a081e2d0f0baac113ec4ee419c00ea1188d0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
