# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


$(document).ready ->
  transition_speed = 400
  listItems = $('#slider').children('li')
  dotItems = $('#dots').children('li')
  listLen = listItems.length
  current = undefined
  changeTimeout = undefined

  moveTo = (newIndex) ->
    i = newIndex
    if newIndex == 'prev'
      i = if current > 0 then current - 1 else listLen - 1
    if newIndex == 'next'
      i = if current < listLen - 1 then current + 1 else 0
    dotItems.removeClass('active').eq(i).addClass 'active'
    listItems.fadeOut(transition_speed).eq(i).fadeIn transition_speed
    current = i
    #resets time interval if user clicks on slider dot; then begin automated slider
    return

  # Event handlers
  $('#dots li').click ->
    i = $('#dots li').index(this)
    moveTo i
    return
  $('#prev').click ->
    moveTo 'prev'
    return
  $('#next').click ->
    moveTo 'next'
    return
  #initialize slider on load
  moveTo 'next'
  return

# ---
# generated by js2coffee 2.2.0